environment:
  matrix:
    - nodejs_version: 5
      TEST_CASSANDRA_VERSION: 3.0.3
os: Visual Studio 2013
platform:
  - x64
install:
  - ps: .\appveyor.ps1
  - npm install
build: off
test_script:
  - npm run ci
cache:
  - node_modules -> package.json
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\jce_policy-8.zip
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\ccm
